[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/recipes"
  to = "/.netlify/functions/recipes"
  status = 200

[[redirects]]
  from = "/api/recipes/search"
  to = "/.netlify/functions/recipes-search"
  status = 200